Update README.MD (Laravel example)
spatie/guzzle-rate-limiter-middleware pull request #22
Opened 2022-02-04 13:52 UTC by EdgarSedov

Old example for laravel leads to out of memory php fatal errors - because it doesn't limit the number of stored items and at the same time doesn't have ttl, so cache is remembered forever.
More than that, thanks to use of array_merge that leads to x2 memory usage (actually x3 because of inner Cache::put realization). So if your cache will have so much data what it weights about 100mb, php will require 300mb of memory during execution of old push method

![image](https://user-images.githubusercontent.com/16332716/152540361-9385f084-2b3e-4c22-be65-4e2539920ccf.png)

2022-04-03 14:42 UTC, EdgarSedov commented
@freekmurze @sebastiandedeyne

2022-04-04 07:47 UTC, freekmurze requested changes
Let's improve readability a bit.

2022-04-04 07:47 UTC, freekmurze commented on README.md
> +        $current = array_slice($this->get(), -($limit + 1));
Put `-($limit + 1))` in a variable with a meaningful name and use that variable.

2022-04-04 07:47 UTC, freekmurze commented on README.md
> +        $current = array_slice($this->get(), -($limit + 1));
Rename `$current` to `items`

2022-04-04 07:47 UTC, freekmurze commented on README.md
> +        Cache::put('rate-limiter', $current, 61);
It's unclear what the meaning of 61 is. Put that in a variable with a meaningful name.

2022-08-05 10:01 UTC, closed without merging